### ISSUE TITLE
JobRequest: Figure out how to handle different patterns: unconnected nodes vs related nodes.

### ISSUE THREAD

**Issue by pbilling** [va-big-data-genomics/trellisdata#5]

**Comment by pbilling** [comment]
The `gatk-5-dollar` one is a weird one, because it's not a traditional dsub job, dsub just creates the Cromwell manager node which reads a separate set of config files to determine inputs/outputs etc.

So, for instance, the Ubam paths are specified as a list in the config file. Right now this config file is generated by the `launch-gatk-5-dollar` function, but in the new model, it would be generated by the dsub script, so I would have to figure out how to pass the paths of each node, as a list, to a dsub variable.

Sigh.

**Comment by pbilling** [comment]
Roadmap

- [ ] Prototype "source" patterns
- [ ] Review every current job launcher and see how they would fit new model
- [ ] Review prototype
- [ ] Identify set of test cases including all observed source patterns
- [ ] Plan logic for implementing source patterns in job launcher function and trellisdata classes

**Comment by pbilling** [comment]
# Sources prototype

```
sources:
  -
    name: fastq_mate_pair
    graph_status: relationship
    pattern: 
      start: Fastq
      rel: HAS_MATE_PAIR
      end: Fastq
    cardinality: one-to-one
  -
    name: ubams
    graph_status: independent
    pattern:
      start: Ubam
    cardinality: many
```
